"""
WHAT THIS SCRIPT DOES
----------------------
Second half of Step 1 (inspection before implementation): looks at the
House of Commons Library's "Free votes in the House of Commons since 1979"
briefing (commonslibrary.parliament.uk/research-briefings/SN04793/),
which reportedly includes a downloadable spreadsheet listing known free
votes. This just finds that spreadsheet and shows what's actually in it —
no cross-referencing against Hansard data yet.

Menu of what happens when you run this file, in order:
  1. Fetch the briefing page's HTML.
  2. Search it for a link to a spreadsheet/document (.xlsx, .xls, .csv,
     .pdf) — parliament.uk research briefing pages usually attach their
     underlying data this way.
  3. Download whatever it finds, and if it's a spreadsheet, print its
     sheet names and the first few rows of each so you can see the real
     column names and date range.

Why this matters: I (Claude) could not reach commonslibrary.parliament.uk
from the sandbox this was written in — blocked by the sandbox's network
policy, same as hansard-api.parliament.uk was. So nothing below has been
verified against the real page yet; this script finds the actual download
link empirically instead of guessing one, but you'll need to run it
somewhere with normal internet access and tell me what it finds.

Usage:
    python explore_free_votes_briefing.py
"""

import argparse
import os
import re

import requests

BRIEFING_URL = "https://commonslibrary.parliament.uk/research-briefings/SN04793/"
SPREADSHEET_EXTENSIONS = (".xlsx", ".xls", ".csv", ".pdf")


def find_attachment_links(html):
    # Looks for href="...something.xlsx" (etc.) anywhere in the page HTML.
    # This is deliberately simple (not a full HTML parser) since all we
    # need is candidate URLs to try downloading.
    hrefs = re.findall(r'href="([^"]+)"', html)
    matches = [h for h in hrefs if h.lower().endswith(SPREADSHEET_EXTENSIONS)]
    # De-duplicate while preserving order.
    seen = set()
    unique = []
    for m in matches:
        if m not in seen:
            seen.add(m)
            unique.append(m)
    return unique


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--briefing-url", default=BRIEFING_URL)
    parser.add_argument("--output-dir", default=".")
    args = parser.parse_args()

    print("=" * 70)
    print(f"Fetching briefing page: {args.briefing_url}")
    print("=" * 70)
    try:
        response = requests.get(args.briefing_url, timeout=20)
    except requests.RequestException as exc:
        print(f"Request failed: {exc}")
        return
    print(f"HTTP {response.status_code}")
    if response.status_code != 200:
        print(f"Response body (first 1000 chars): {response.text[:1000]}")
        return

    links = find_attachment_links(response.text)
    if not links:
        print("No .xlsx/.xls/.csv/.pdf links found directly in the page HTML.")
        print("The download link might be generated by JavaScript, or under a")
        print("different path — try opening the page in a browser and look for")
        print("a 'Download' button, then pass its URL to this script, e.g.:")
        print(f"  python {os.path.basename(__file__)} --briefing-url <the real link>")
        return

    print(f"Found {len(links)} candidate attachment link(s):")
    for link in links:
        print(f"  {link}")

    # Try downloading the first one.
    target = links[0]
    if not target.startswith("http"):
        # Relative link — resolve it against the briefing page's domain.
        from urllib.parse import urljoin
        target = urljoin(args.briefing_url, target)

    print()
    print(f"Downloading: {target}")
    try:
        file_response = requests.get(target, timeout=30)
    except requests.RequestException as exc:
        print(f"Download failed: {exc}")
        return
    print(f"HTTP {file_response.status_code}")
    if file_response.status_code != 200:
        return

    filename = os.path.join(args.output_dir, os.path.basename(target.split("?")[0]))
    with open(filename, "wb") as f:
        f.write(file_response.content)
    print(f"Saved to {filename}")

    if filename.lower().endswith((".xlsx", ".xls")):
        try:
            import pandas as pd
        except ImportError:
            print("Install pandas + openpyxl to auto-inspect the spreadsheet: "
                  "pip install pandas openpyxl")
            return
        sheets = pd.read_excel(filename, sheet_name=None)
        print(f"\nSpreadsheet has {len(sheets)} sheet(s): {list(sheets.keys())}")
        for name, df in sheets.items():
            print(f"\n--- Sheet '{name}' ---")
            print(f"Columns: {list(df.columns)}")
            print(f"Rows: {len(df)}")
            print(df.head(5).to_string())
    elif filename.lower().endswith(".csv"):
        try:
            import pandas as pd
            df = pd.read_csv(filename)
            print(f"\nColumns: {list(df.columns)}")
            print(f"Rows: {len(df)}")
            print(df.head(5).to_string())
        except ImportError:
            print("Install pandas to auto-inspect the CSV: pip install pandas")
    elif filename.lower().endswith(".pdf"):
        print("\nDownloaded a PDF, not a spreadsheet — free-vote entries would need "
              "to be extracted from text/tables rather than read directly as data. "
              "Open it and check whether it's actually a list/table or prose.")


if __name__ == "__main__":
    main()
